stages:
  - iaac-validate

stages:
  - iaac-validate
  - iaac-apply



iaac-validate:
  stage: iaac-validate
  script:
    - /usr/local/bin/terraform init -var access_key="AKIAWPE56Y6CL7JG5N7P" -var secret_key="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" 
    - /usr/local/bin/terraform plan -var access_key="AKIAWPE56Y6CL7JG5N7P" -var secret_key="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" -out "planfile"
    - /usr/local/bin/terraform validate -var-file variables.tfvars
    
  artifacts:
    paths:
      - planfile    
  tags:
    - myrunner
    
apply:
  stage: iaac-apply
  script:
    - /usr/local/bin/terraform init -backend-config "access_key=AKIAWPE56Y6CL7JG5N7P" -backend-config "secret_key=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"
    - /usr/local/bin/terraform apply "planfile" 
  tags:
    - myrunner
  artifacts:
    paths:

