---
- name: Install Unzip.
  apt:
    name: unzip
    state: latest

- name: Update apt-get repo and cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade apt-get all packages.
  apt:
    name: "*"
    state: latest

- name: Install extra packages.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - software-properties-common
    - curl
    - wget
    - git
   # - gcc
   # - make
    - gnupg2
    - ca-certificates
    - lsb-release
    - libmysqlclient-dev
